/* Reference textbooks cited across MedBridge. `book` keys are used by the
   `textbook` arrays on drugs (drugs-data.js) and cases (conditions.js). */
window.BOOKS = {
  harrison: { title: "Harrison's Principles of Internal Medicine", edition: "22nd ed.", year: 2025, scope: "Adult medicine" },
  williams: { title: "Williams Obstetrics", edition: "25th ed.", year: 2018, scope: "Obstetrics" },
  gabbe:    { title: "Gabbe's Obstetrics: Normal and Problem Pregnancies", edition: "9th ed.", year: 2025, scope: "Obstetrics" },
  schwartz: { title: "Schwartz's Principles of Surgery", edition: "11th ed.", year: 2019, scope: "Surgery, trauma and anaesthesia" },
  nelson:   { title: "Nelson Textbook of Pediatrics", edition: "22nd ed.", year: 2024, scope: "Paediatrics and neonatology" },
  kaplan:   { title: "Kaplan & Sadock's Synopsis of Psychiatry", edition: "12th ed.", year: 2022, scope: "Psychiatry and psychopharmacology" },
  dsm:      { title: "DSM-5-TR Clinical Cases", edition: "", year: 2023, scope: "Psychiatric diagnosis (American Psychiatric Association)" },
  bcsc:     { title: "Basic and Clinical Science Course, Section 3: Clinical Optics", edition: "2019–2020", year: null, scope: "Optics, refraction, contact lenses and low vision (American Academy of Ophthalmology)" },
  whovl:    { title: "WHO guideline for the treatment of visceral leishmaniasis in HIV co-infected patients in East Africa and South-East Asia", edition: "", year: 2022, scope: "Visceral leishmaniasis with HIV" },
  whovl26:  { title: "WHO guidelines on leishmaniases: treatment of visceral leishmaniasis and post-kala-azar dermal leishmaniasis in eastern Africa and South-East Asia", edition: "", year: 2026, scope: "Kala-azar and PKDL treatment in people without HIV — the current WHO guideline" },
  ethmal:   { title: "Malaria case management training manual (Ministry of Health, Ethiopia)", edition: "", year: 2024, scope: "The Ethiopian national malaria protocol: diagnosis, first- and second-line treatment, severe malaria, pregnancy (from the National Malaria Guidelines 2022)" },
  whomal:   { title: "WHO guidelines for malaria", edition: "10 September 2026", year: null, scope: "Malaria prevention, diagnosis and treatment — the current WHO guideline" },
  ethhiv:   { title: "National Comprehensive HIV Prevention, Care and Treatment Training — Participant Manual (Ministry of Health, Ethiopia)", edition: "", year: 2025, scope: "The Ethiopian national HIV protocol: testing, ART, monitoring, PMTCT, PEP, PrEP, advanced disease and opportunistic infections" },
  whohivclin:{ title: "WHO updated recommendations on HIV clinical management", edition: "", year: 2025, scope: "Recent WHO changes to antiretroviral therapy and HIV clinical care" },
  whohivsti:{ title: "Overview of WHO recommendations on HIV and sexually transmitted infection testing, prevention, treatment, care and service delivery", edition: "", year: 2025, scope: "A summary of current WHO HIV and STI recommendations" },
  whopph:   { title: "WHO consolidated guidelines for the prevention, diagnosis and treatment of postpartum haemorrhage", edition: "", year: 2025, scope: "Postpartum haemorrhage — the current WHO guideline, superseding the 2012 recommendations" },
  whobundle:{ title: "WHO recommendations on the assessment of postpartum blood loss and use of a treatment bundle for postpartum haemorrhage", edition: "", year: 2023, scope: "Measuring blood loss and the E-MOTIVE first-response bundle" },
  ethpph:   { title: "National guideline on prevention and management of postpartum haemorrhage (Ministry of Health, Ethiopia)", edition: "", year: 2022, scope: "The Ethiopian national PPH protocol" },
  figopph:  { title: "FIGO guidelines: prevention and treatment of postpartum haemorrhage in low-resource settings", edition: "Int J Gynecol Obstet 117", year: 2012, scope: "PPH where theatre, blood and an anaesthetist may be far away" },
  whosepsis:{ title: "WHO Managing puerperal sepsis (midwifery education modules)", edition: "2nd ed.", year: 2006, scope: "Puerperal sepsis: recognition, treatment and prevention" },
  ethepi:   { title: "Routine immunization catch-up vaccination guidelines (Ministry of Health, Ethiopia)", edition: "", year: 2022, scope: "Catch-up immunisation: minimum ages, minimum intervals and upper age limits" },
  asellaor: { title: "List of OR materials for surgical cases, Asella Referral and Teaching Hospital", edition: "", year: 2025, scope: "What to have ready in theatre for each operation — institutional practice, not a guideline" },
  ichem:    { title: "Acute management of spontaneous intracerebral hemorrhage (ICH) in the emergency department", edition: "Puissant & Ganti, Int J Emerg Med 19:35", year: 2026, scope: "Emergency care of brain haemorrhage — a review of the 2022 AHA/ASA guideline" },
  bmjksd:   { title: "Practical Prescribing: Potassium sparing diuretics", edition: "Anisman, Erickson & Luneau, BMJ 392:e085905", year: 2026, scope: "Spironolactone, eplerenone, finerenone, amiloride and triamterene in practice" },
  ahastats: { title: "Heart Disease and Stroke Statistics: A Report of US and Global Data from the American Heart Association", edition: "Circulation 153", year: 2026, scope: "How common heart disease and stroke are, and how many die of them, in the US and worldwide" },
  note:     { title: "Editorial notes", edition: "", year: null, scope: "Where the textbooks differ from low-resource practice or are silent" }
};
