/* ============================================================
   MedBridge "never mix" reference — line, syringe and fluid
   incompatibilities that cause harm. DRAFT until reviewed.
   An absence here does NOT mean two drugs are compatible.
   ============================================================ */
window.COMPAT = [
  { a: ["calcium-gluconate"], b: ["sodium-bicarbonate"], severity: "never",
    what: "Calcium and bicarbonate form insoluble calcium carbonate that blocks the line and can embolise.",
    do: "Separate lines, or flush with at least 10 mL of 0.9 % saline between them.",
    ref: "Nelson 22nd ed., Table 79.5; drug entries" },
  { a: ["ceftriaxone"], b: ["calcium-gluconate", "ringers-lactate"], severity: "never",
    what: "Ceftriaxone precipitates with calcium. Fatal lung and kidney precipitates have occurred in neonates.",
    do: "Neonates: never give ceftriaxone with any calcium-containing fluid, even in separate lines. Older patients: flush thoroughly between them, never in the same line at the same time.",
    ref: "Ceftriaxone product information; WHO Pocket Book 2013" },
  { a: ["phenytoin"], b: ["dextrose"], severity: "never",
    what: "Phenytoin crystallises in any glucose solution; the patient receives little drug and the cannula blocks.",
    do: "Dilute only in 0.9 % saline; flush with saline before and after.",
    ref: "Phenytoin product information; drug entry" },
  { a: ["diazepam"], b: ["*"], severity: "caution",
    what: "Diazepam precipitates when diluted in IV fluids and binds to PVC tubing.",
    do: "Give undiluted, slowly, into a running saline line close to the cannula. Do not add it to a bag.",
    ref: "Diazepam product information" },
  { a: ["adrenaline", "noradrenaline", "dopamine"], b: ["sodium-bicarbonate"], severity: "never",
    what: "Catecholamines are inactivated in alkaline solutions.",
    do: "Separate line for any vasopressor; never flush a vasopressor line.",
    ref: "Product information; drug entries" },
  { a: ["amiodarone"], b: ["ringers-lactate"], severity: "caution",
    what: "Amiodarone infusions are prepared in 5 % glucose; it is unstable in saline-based infusion and leaches plasticiser from PVC.",
    do: "Dilute infusions in 5 % glucose only; use a large vein (phlebitis).",
    ref: "Amiodarone product information; drug entry" },
  { a: ["blood-transfusion"], b: ["dextrose", "ringers-lactate", "calcium-gluconate"], severity: "never",
    what: "Dextrose haemolyses red cells; calcium (including Ringer's lactate) makes stored blood clot in the line.",
    do: "Only 0.9 % saline may run in the same line as blood. Never add drugs to a blood bag.",
    ref: "WHO The Clinical Use of Blood; drug entry" },
  { a: ["gentamicin"], b: ["ampicillin", "benzylpenicillin", "cloxacillin"], severity: "never",
    what: "Penicillins inactivate aminoglycosides when mixed.",
    do: "Never in the same syringe or bag. Give separately and flush between them.",
    ref: "BNF / product information" },
  { a: ["gentamicin"], b: ["heparin"], severity: "caution",
    what: "Gentamicin and heparin precipitate when mixed.",
    do: "Flush a heparin-locked line with saline before giving gentamicin.",
    ref: "Product information" },
  { a: ["insulin-soluble"], b: ["*"], severity: "caution",
    what: "Insulin binds to plastic bags and tubing, so the first part of an infusion delivers much less than expected.",
    do: "Prime by running 50 mL of the insulin solution through the line and discarding it. Give insulin through its own line.",
    ref: "Drug entry" },
  { a: ["potassium-chloride"], b: ["dextrose"], severity: "caution",
    what: "Dextrose triggers insulin release that drives potassium into cells and can worsen hypokalaemia.",
    do: "Add potassium to 0.9 % saline. Never add potassium to a hanging bag — mix the bag off the stand.",
    ref: "Harrison 22nd ed., ch. 55, p. 400" },
  { a: ["hydralazine"], b: ["dextrose"], severity: "caution",
    what: "Hydralazine is unstable in glucose solutions.",
    do: "Reconstitute with water for injection and dilute in 0.9 % saline.",
    ref: "Hydralazine product information" },
  { a: ["ampicillin"], b: ["dextrose"], severity: "caution",
    what: "Ampicillin degrades quickly once reconstituted, faster in glucose solutions.",
    do: "Reconstitute just before use, dilute in saline, give within 1 hour.",
    ref: "Ampicillin product information; drug entry" },
  { a: ["phenobarbital"], b: ["*"], severity: "caution",
    what: "Phenobarbital injection is strongly alkaline and precipitates with many acidic drugs.",
    do: "Give on its own, flushing the line with saline before and after.",
    ref: "Product information" },
  { a: ["oxytocin"], b: ["dextrose"], severity: "caution",
    what: "Large volumes of oxytocin in dextrose or water cause water intoxication and hyponatraemia.",
    do: "Use 0.9 % saline or Ringer's lactate; limit total volume (maximum 3 L of oxytocin-containing fluid in PPH).",
    ref: "WHO MCPC 2017; Williams Obstetrics 25th ed." },
  { a: ["metronidazole"], b: ["*"], severity: "caution",
    what: "The ready-made metronidazole bag should not have other drugs added to it.",
    do: "Run it alone over 20–30 minutes.",
    ref: "Drug entry" },
  {a: ["mannitol"],b: ["blood-transfusion"],severity: "never",what: "Mannitol causes red-cell crenation and clumping (pseudo-agglutination) in the giving set.",do: "Never run mannitol through a line with blood or blood products. Use a separate line, or flush thoroughly with 0.9 % saline.",ref: "Mannitol product information; WHO The Clinical Use of Blood"},
  {a: ["mannitol"],b: ["potassium-chloride","hypertonic-saline"],severity: "caution",what: "Adding potassium chloride or sodium chloride to 20 % mannitol can make the mannitol crystallise out of solution.",do: "Give mannitol on its own; do not add electrolytes to the mannitol bottle. Inspect for crystals and use a filter.",ref: "Mannitol 20 % product information"},
  {a: ["adenosine"],b: ["aminophylline","caffeine-citrate"],severity: "caution",what: "Methylxanthines block adenosine receptors, so adenosine may fail in a patient on aminophylline or a baby on caffeine.",do: "Expect to need the higher dose; move to synchronised cardioversion rather than repeated doses if it fails.",ref: "Adenosine product information; BNF"},
  {a: ["snake-antivenom"],b: ["*"],severity: "caution",what: "Antivenom is a foreign protein infusion; mixing drugs into it makes reactions impossible to attribute and may denature it.",do: "Run antivenom through its own line; give adrenaline, antihistamine and steroid separately.",ref: "Antivenom product information; WHO snakebite guidelines"},
  {a: ["fluphenazine-decanoate"],b: ["*"],severity: "never",what: "Oily depot in sesame oil. It must never be given IV or subcutaneously, and it does not mix with water-based injections in a syringe.",do: "Deep IM only, alone in its own syringe. Aspirate before injecting. Never mix with any other drug.",ref: "Fluphenazine decanoate product information (SmPC); drug entry"},
  {a: ["olanzapine"],b: ["diazepam","lorazepam","haloperidol"],severity: "never",what: "Olanzapine IM powder precipitates with diazepam injection, reconstitutes poorly with lorazepam injection, and is degraded by the low pH of haloperidol injection.",do: "Reconstitute olanzapine only with 2.1 mL water for injection. Never combine in a syringe with another drug. Separate injection sites; for benzodiazepines also keep the 1-hour gap (see interactions).",ref: "Olanzapine powder for solution for injection, product information (SmPC)"},
  {a: ["haloperidol"],b: ["promethazine"],severity: "caution",what: "Often given together for rapid tranquillisation, but compatibility in one syringe is not reliably established.",do: "Draw up in separate syringes and inject into different sites.",ref: "No reliable compatibility data in product information; NICE NG10 describes two IM injections"},
  {a: ["promethazine"],b: ["*"],severity: "caution",what: "Promethazine injection is highly irritant. Subcutaneous, intra-arterial or perivascular injection causes severe tissue injury and gangrene.",do: "Deep IM is the preferred route. IV only if essential: no stronger than 25 mg/mL, no faster than 25 mg per minute, into a freely running line in a large vein. Stop at once if there is pain or burning.",ref: "US FDA boxed warning, promethazine injection (2009); product information"},
  {a: ["lorazepam"],b: ["*"],severity: "caution",what: "Lorazepam injection is viscous (propylene glycol and polyethylene glycol vehicle).",do: "Dilute with an equal volume of 0.9 % saline or water for injection immediately before IM or IV use. Give IV slowly, no faster than 2 mg per minute. Do not add to other drugs in a syringe.",ref: "Lorazepam injection product information (SmPC and US label)"},
  {a: ["thiamine"],b: ["sodium-bicarbonate"],severity: "caution",what: "Thiamine is unstable in alkaline or neutral solutions and breaks down when mixed with carbonates or bicarbonate; the patient receives less thiamine.",do: "Do not mix thiamine in the same syringe, bag or line as sodium bicarbonate. Give thiamine in 0.9 % saline or 5 % glucose, flushing the line before and after.",ref: "Thiamine hydrochloride injection product information"},
  {a: ["haloperidol-decanoate"],b: ["*"],severity: "never",what: "Oily depot in sesame oil. It must never be given IV or subcutaneously, and it does not mix with water-based injections in a syringe.",do: "Deep IM only, alone in its own syringe. Aspirate before injecting. Never mix with any other drug, including short-acting haloperidol lactate.",ref: "Haloperidol decanoate product information (SmPC and US label); drug entry"},
  {a: ["risperidone"],b: ["*"],severity: "caution",what: "The long-acting risperidone injection (Consta) is a microsphere suspension that must be made up only with the diluent supplied and given at once; other diluents or added drugs spoil the suspension and the dose released.",do: "Reconstitute only with the supplied diluent, use the supplied needle, inject the whole vial deep IM straight away, and never mix with another drug. Oral risperidone tablets and solution are unaffected.",ref: "Risperdal Consta product information (SmPC)"},

  /* ---- amphotericin B ---- */
  {
    a: ["liposomal-amphotericin-b", "amphotericin-b-deoxycholate"],
    b: ["ringers-lactate", "hypertonic-saline"],
    severity: "never",
    what: "Amphotericin B products are incompatible with saline and with any electrolyte solution. Liposomal amphotericin B must be reconstituted with water for injection and diluted only in 5 % dextrose — saline makes the liposomes aggregate. Amphotericin B deoxycholate precipitates outright in saline and in Ringer's lactate. Either way the patient gets little drug and the line blocks.",
    do: "Dilute in 5 % dextrose only. Never use 0.9 % saline, Ringer's lactate or any electrolyte-containing fluid to reconstitute, dilute or flush an amphotericin line. If the same cannula must carry saline for something else, finish the saline, flush with 5 % dextrose, then start the amphotericin. If the infusion has to be slowed or paused, keep the line open with dextrose.",
    ref: "AmBisome and amphotericin B deoxycholate product information; WHO guideline: visceral leishmaniasis in HIV co-infected patients (2022), 5.2.1, pdf p. 55"
  },
  {
    a: ["liposomal-amphotericin-b", "amphotericin-b-deoxycholate"],
    b: ["*"],
    severity: "never",
    what: "No other drug may be added to an amphotericin B bag or syringe, and nothing else should share the line. It is a colloidal or liposomal preparation, and any additive can break it; its long infusion also makes it tempting to piggyback other drugs onto the same line.",
    do: "Amphotericin B runs alone, in its own bag, over 2 h (liposomal) or 4–6 h (deoxycholate). Give everything else through a second cannula, or before and after with a 5 % dextrose flush in between. Do not add potassium to the amphotericin bag — give potassium separately.",
    ref: "AmBisome product information; drug entry"
  },
  {
    a: ["liposomal-amphotericin-b"],
    b: ["blood-transfusion"],
    severity: "never",
    what: "Blood may only run with 0.9 % saline, and amphotericin B may never touch saline — the two requirements cannot be met in one line. Acute pulmonary toxicity has also been reported when intravenous amphotericin B was given at the same time as leukocyte transfusions.",
    do: "Use a separate cannula for the transfusion. Never run an amphotericin infusion into a line carrying blood or blood products, and do not give the two simultaneously through a Y-connector.",
    ref: "WHO guideline: visceral leishmaniasis in HIV co-infected patients (2022), 5.3.1, pdf p. 60; WHO The Clinical Use of Blood"
  },
  {
    a: ["sodium-stibogluconate"],
    b: ["*"],
    severity: "caution",
    what: "Sodium stibogluconate is supplied as a concentrated multi-dose vial for IM or slow IV use. Compatibility with other injectables is not established, and it is usually drawn up neat for intramuscular injection.",
    do: "Give it alone, in its own syringe and its own site. If the IV route is needed, dilute only in 5 % dextrose and give over 20–30 min, or slowly into a running drip — nothing else in that line. Never mix it in a syringe with paromomycin: give the two in different sites on the same day.",
    ref: "Sodium stibogluconate product information; WHO guideline: visceral leishmaniasis in HIV co-infected patients (2022), Annex 2, pdf p. 83"
  },
  {
    a: ["paromomycin"],
    b: ["sodium-stibogluconate", "ampicillin", "benzylpenicillin", "cloxacillin", "heparin"],
    severity: "never",
    what: "Paromomycin is an aminoglycoside. Penicillins inactivate aminoglycosides when mixed in a syringe or bag, and aminoglycosides precipitate with heparin. Mixing it with sodium stibogluconate in one syringe is untested and adds two different injection-site toxicities to one site.",
    do: "Never in the same syringe. Paromomycin goes deep IM on its own, in a different site from the antimonial, with both rotated on a written four-site chart. Flush a heparin-locked line with 0.9 % saline before any aminoglycoside.",
    ref: "BNF / aminoglycoside product information; drug entry"
  },

  /* ---- ophthalmic drugs ---- */
  {
    a: ["acetazolamide"],
    b: ["*"],
    severity: "caution",
    what: "Reconstituted acetazolamide for injection is strongly alkaline (pH about 9.0–9.6). Mixed in a syringe or a running line with acidic drugs it can precipitate, and the precipitate is not always visible against a brown giving set.",
    do: "Reconstitute the 500 mg vial with 5 mL water for injection (100 mg/mL) and give it as a slow IV push over 1–2 minutes into a line flushed with 0.9 % saline before and after. Do not add it to an infusion bag with other drugs and do not give it in the same syringe as anything else. Use it immediately after reconstitution.",
    ref: "Acetazolamide sodium for injection product information; drug entry"
  }
];
